substitutions:
  GRAY_0:  "0x000000"
  GRAY_1:  "0x111111"
  GRAY_2:  "0x222222"
  GRAY_3:  "0x333333"
  GRAY_4:  "0x444444"
  GRAY_5:  "0x555555"
  GRAY_6:  "0x666666"
  GRAY_7:  "0x777777"
  GRAY_8:  "0x888888"
  GRAY_9:  "0x999999"
  GRAY_A:  "0xAAAAAA"
  GRAY_B:  "0xBBBBBB"
  GRAY_C:  "0xCCCCCC"
  GRAY_D:  "0xDDDDDD"
  GRAY_E:  "0xEEEEEE"
  GRAY_F:  "0xFFFFFF"

  COL_BG:          "${GRAY_E}"
  COL_SURFACE:     "${GRAY_F}"
  COL_BORDER:      "${GRAY_B}"
  COL_DIVIDER:     "${GRAY_C}"
  COL_TEXT:        "${GRAY_0}"
  COL_TEXT_MUTED:  "${GRAY_7}"
  COL_FILL:        "${GRAY_3}"
  COL_FILL_LIGHT:  "${GRAY_D}"