substitutions:
  ICO_CHEV_L: "\U000F0141" # mdi:chevron-left
  ICO_CHEV_R: "\U000F0142"
  ICO_CHEV_D: "\U000F0140" # mdi:chevron-down
  ICO_HOME:   "\U000F02DC" #mdi:home

  ICO_MORE: "\U000F01D8"   # requested icon

  ICO_KITCHEN:  "\U000F181C"
  ICO_ARTHUR:   "\U000F0E7D"
  ICO_CLEANING: "\U000F19A2"
  ICO_BEDROOM:  "\U000F0FD1"
  ICO_LIVING:   "\U000F156D"
  ICO_HEATING:  "\U000F1A45"
  ICO_WEATHER:  "\U000F18D6"
  ICO_HALLWAY:  "\U000F0DFA"
  ICO_BATHROOM: "\U000F1819"

  ICO_PRESET_FROST:   "\U000F1A71"   # F1A71
  ICO_PRESET_ECO:     "\U000F032A"   # F032A
  ICO_PRESET_COMFORT: "\U000F04B9"   # F04B9
  ICO_PRESET_BOOST:   "\U000F14DE"   # F14DE
 # ICO_HVAC_MODE:     "\U000F0425"   # F0425 (power icon)
  ICO_HVAC_MODE:      "\U000F1A45"   # F0425 (heat icon)

  # -------------------------
  # Cleaning / Vacuum controls
  # -------------------------
  ICO_VAC_PLAY:  "\U000F040A"  # mdi:play
  ICO_VAC_PAUSE: "\U000F03E4"  # mdi:pause
  ICO_VAC_DOCK:  "\U000F0F9C"  # mdi:home-import-outline
  ICO_VAC_TRASH: "\U000F0A79"  # mdi:trash-can-outline

  ICO_NUM_1_CIRCLE: "\U000F0CA0"  # mdi:numeric-1-circle
  ICO_NUM_2_CIRCLE: "\U000F0CA2"  # mdi:numeric-2-circle

  ICO_WIFI: "\U000F05A9"      # mdi-wifi
  ICO_WIFI_OFF: "\U000F092B"   # mdi-wifi-off

  # -------------------------
  # ThinkLab (Proxmox/LXCs)
  # -------------------------
  ICO_TL_BOOK:          "\U000F05DA"  # mdi:book-open-page-variant
  ICO_TL_FILM:          "\U000F0230"  # mdi:filmstrip
  ICO_TL_SHIELD_CHECK:  "\U000F0CC8"  # mdi:shield-check
  ICO_TL_FOLDER_NET:    "\U000F0870"  # mdi:folder-network
  ICO_TL_CLOUD_LOCK:    "\U000F11F1"  # mdi:cloud-lock
  ICO_TL_BABY:          "\U000F006C"  # mdi:baby
  ICO_TL_HA:            "\U000F07D0"  # mdi:home-assistant